indentation = "  "
line_ending = "Auto"
space_after_comma = true

[uses_section]
uses_section_style = "CommaAtTheEnd"
override_sorting_order = []
module_names_to_update = []

[transformations]
enable_uses_section = true
enable_unit_program_section = false
enable_single_keyword_sections = true
enable_procedure_section = true