indentation = "  "
line_ending = "Auto"
exclude_files = []
custom_config_patterns = []

[uses_section]
uses_section_style = "CommaAtTheEnd"
override_sorting_order = []
module_names_to_update = [
    "System:Actions",
    "System:Analytics.AppAnalytics",
    "System:Analytics",
    "System:AnsiStrings",
    "System:Character",
    "System:Classes",
    "System:Contnrs",
    "System:ConvUtils",
    "System:Curl",
    "System:DateUtils",
    "System:Devices",
    "System:Diagnostics",
    "System:Generics.Collections",
    "System:Generics.Defaults",
    "System:Hash",
    "System:HelpIntfs",
    "System:IOUtils",
    "System:ImageList",
    "System:IniFiles",
    "System:Internal.DebugUtils",
    "System:Internal.ICU",
    "System:JSON.BSON",
    "System:JSON.Builders",
    "System:JSON.Converters",
    "System:JSON.Readers",
    "System:JSON.Serializers",
    "System:JSON.Types",
    "System:JSON.Utils",
    "System:JSON.Writers",
    "System:JSON",
    "System:JSONConsts",
    "System:MaskUtils",
    "System:Masks",
    "System:Math.Vectors",
    "System:Math",
    "System:Messaging",
    "System:NetEncoding.Sqids",
    "System:NetEncoding",
    "System:Notification",
    "System:ObjAuto",
    "System:Odbc",
    "System:Permissions",
    "System:PushNotification",
    "System:RTLConsts",
    "System:RegularExpressions",
    "System:RegularExpressionsAPI",
    "System:RegularExpressionsConsts",
    "System:RegularExpressionsCore",
    "System:Rtti",
    "System:Sensors.Components",
    "System:Sensors",
    "System:Skia.API",
    "System:Skia",
    "System:Sqlite",
    "System:StartUpCopy",
    "System:StdConvs",
    "System:StrUtils",
    "System:SyncObjs",
    "System:SysUtils",
    "System:Threading",
    "System:TimeSpan",
    "System:TypInfo",
    "System:UIConsts",
    "System:UITypes",
    "System:VarCmplx",
    "System:VarConv",
    "System:Vulkan",
    "System:WideStrUtils",
    "System:WideStrings",
    "System:Win.ComConst",
    "System:Win.ComObj",
    "System:Win.ComObjWrapper",
    "System:Win.ComServ",
    "System:Win.Crtl",
    "System:Win.Devices",
    "System:Win.HighDpi",
    "System:Win.IEInterfaces",
    "System:Win.InternetExplorer",
    "System:Win.Mtsobj",
    "System:Win.Notification",
    "System:Win.ObjComAuto",
    "System:Win.OleControls",
    "System:Win.OleServers",
    "System:Win.Registry",
    "System:Win.ScktComp",
    "System:Win.Sensors",
    "System:Win.ShareContract",
    "System:Win.StdVCL",
    "System:Win.Taskbar",
    "System:Win.TaskbarCore",
    "System:Win.VCLCom",
    "System:Win.WinRT",
    "System:ZLib",
    "System:ZLibConst",
    "System:Zip",
    "System.Win:ComConst",
    "System.Win:ComObj",
    "System.Win:ComObjWrapper",
    "System.Win:ComServ",
    "System.Win:Crtl",
    "System.Win:Devices",
    "System.Win:HighDpi",
    "System.Win:IEInterfaces",
    "System.Win:InternetExplorer",
    "System.Win:Mtsobj",
    "System.Win:Notification",
    "System.Win:ObjComAuto",
    "System.Win:OleControls",
    "System.Win:OleServers",
    "System.Win:Registry",
    "System.Win:ScktComp",
    "System.Win:Sensors",
    "System.Win:ShareContract",
    "System.Win:StdVCL",
    "System.Win:Taskbar",
    "System.Win:TaskbarCore",
    "System.Win:VCLCom",
    "System.Win:WinRT",
    "Winapi:ADOInt",
    "Winapi:AccCtrl",
    "Winapi:AclAPI",
    "Winapi:ActiveX",
    "Winapi:AspTlb",
    "Winapi:Bluetooth",
    "Winapi:BluetoothLE",
    "Winapi:COMAdmin",
    "Winapi:ComSvcs",
    "Winapi:CommCtrl",
    "Winapi:CommDlg",
    "Winapi:Cor",
    "Winapi:CorError",
    "Winapi:CorHdr",
    "Winapi:Cpl",
    "Winapi:D2D1",
    "Winapi:D3D10",
    "Winapi:D3D10_1",
    "Winapi:D3D11",
    "Winapi:D3D11Shader",
    "Winapi:D3D11Shadertracing",
    "Winapi:D3D11_1",
    "Winapi:D3D11_2",
    "Winapi:D3D11_3",
    "Winapi:D3D11on12",
    "Winapi:D3D11sdklayers",
    "Winapi:D3D12",
    "Winapi:D3D12Shader",
    "Winapi:D3D12sdklayers",
    "Winapi:D3DCommon",
    "Winapi:D3DCompiler",
    "Winapi:D3DX10",
    "Winapi:D3DX8",
    "Winapi:D3DX9",
    "Winapi:DDEml",
    "Winapi:DX7toDX8",
    "Winapi:DXFile",
    "Winapi:DXGI",
    "Winapi:DXGI1_2",
    "Winapi:DXGI1_3",
    "Winapi:DXGI1_4",
    "Winapi:DXTypes",
    "Winapi:Direct3D.PkgHelper",
    "Winapi:Direct3D",
    "Winapi:Direct3D8",
    "Winapi:Direct3D9",
    "Winapi:DirectDraw",
    "Winapi:DirectInput",
    "Winapi:DirectMusic",
    "Winapi:DirectPlay8",
    "Winapi:DirectShow9",
    "Winapi:DirectSound",
    "Winapi:Dlgs",
    "Winapi:DwmApi",
    "Winapi:DxDiag",
    "Winapi:DxgiFormat",
    "Winapi:DxgiType",
    "Winapi:EdgeUtils",
    "Winapi:FlatSB",
    "Winapi:Functiondiscovery",
    "Winapi:GDIPAPI",
    "Winapi:GDIPOBJ",
    "Winapi:GDIPUTIL",
    "Winapi:ImageHlp",
    "Winapi:Imm",
    "Winapi:IpExport",
    "Winapi:IpHlpApi",
    "Winapi:IpRtrMib",
    "Winapi:IpTypes",
    "Winapi:Isapi",
    "Winapi:Isapi2",
    "Winapi:KnownFolders",
    "Winapi:LZExpand",
    "Winapi:Locationapi",
    "Winapi:MLang",
    "Winapi:MMSystem",
    "Winapi:Manipulations",
    "Winapi:Mapi",
    "Winapi:Messages",
    "Winapi:MsCTF.PkgHelper",
    "Winapi:MsCTF",
    "Winapi:MsInkAut",
    "Winapi:MsInkAut15",
    "Winapi:Mshtmhst",
    "Winapi:Mtx",
    "Winapi:MultiMon",
    "Winapi:Nb30",
    "Winapi:ObjectArray",
    "Winapi:Ole2",
    "Winapi:OleCtl",
    "Winapi:OleDB",
    "Winapi:OleDlg",
    "Winapi:OpenGL.PkgHelper",
    "Winapi:OpenGL",
    "Winapi:OpenGLext",
    "Winapi:PenInputPanel",
    "Winapi:Penwin",
    "Winapi:Portabledevicetypes",
    "Winapi:PropKey",
    "Winapi:PropSys",
    "Winapi:PsAPI",
    "Winapi:Qos",
    "Winapi:RegStr",
    "Winapi:RichEdit",
    "Winapi:RtsCom",
    "Winapi:SHFolder",
    "Winapi:Sensors",
    "Winapi:Sensorsapi",
    "Winapi:ShLwApi",
    "Winapi:ShellAPI",
    "Winapi:ShellScaling",
    "Winapi:ShlObj",
    "Winapi:StructuredQuery",
    "Winapi:StructuredQueryCondition",
    "Winapi:TlHelp32",
    "Winapi:TpcShrd",
    "Winapi:UrlMon",
    "Winapi:UserEnv",
    "Winapi:UxTheme",
    "Winapi:Vulkan",
    "Winapi:WMF9",
    "Winapi:WTSApi32",
    "Winapi:Wbem",
    "Winapi:WebView2",
    "Winapi:WinCred",
    "Winapi:WinHTTP",
    "Winapi:WinInet",
    "Winapi:WinSock",
    "Winapi:WinSpool",
    "Winapi:WinSvc",
    "Winapi:Wincodec",
    "Winapi:Windows.PkgHelper",
    "Winapi:Windows",
    "Winapi:Winrt",
    "Winapi:WinrtMetadata",
    "Winapi:Winsafer",
    "Winapi:Winsock2",
    "Winapi:msxml",
    "Winapi:msxmlIntf",
    "Winapi:oleacc",
]

[transformations]
enable_uses_section = true
enable_unit_program_section = true
enable_single_keyword_sections = true
enable_procedure_section = true
enable_text_transformations = false

[text_changes]
comma = "After"
semi_colon = "After"
lt = "BeforeAndAfter"
eq = "BeforeAndAfter"
neq = "BeforeAndAfter"
gt = "BeforeAndAfter"
lte = "BeforeAndAfter"
gte = "BeforeAndAfter"
add = "BeforeAndAfter"
sub = "BeforeAndAfter"
mul = "BeforeAndAfter"
fdiv = "BeforeAndAfter"
assign = "BeforeAndAfter"
assign_add = "BeforeAndAfter"
assign_sub = "BeforeAndAfter"
assign_mul = "BeforeAndAfter"
assign_div = "BeforeAndAfter"
colon = "After"
colon_numeric_exception = true
trim_trailing_whitespace = true
