indentation = "  "
line_ending = "Auto"

[transformations]
enable_inline_local_var_definitions = false
enable_uses_section = false
enable_unit_program_section = false
enable_single_keyword_sections = false
enable_procedure_section = false
enable_local_routine_spacing = false
enable_local_routine_indentation = false
enable_for_body_wrapping = true
enable_while_body_wrapping = true
enable_if_body_wrapping = true
skip_terminating_for_body_wrapping = true
skip_terminating_while_body_wrapping = true
skip_terminating_if_body_wrapping = false
enable_inherited_call_expansion = false
enable_text_transformations = false
