indentation = "  "
line_ending = "Auto"

[transformations]
enable_uses_section = false
enable_unit_program_section = false
enable_single_keyword_sections = false
enable_procedure_section = false
enable_local_routine_spacing = false
enable_local_routine_indentation = false
enable_control_statement_body_wrapping = true
enable_inherited_call_expansion = false
enable_text_transformations = false
